### ISSUE TITLE
Template not yet loaded

### ISSUE THREAD

**Issue by yesmaybe** [planadecu/gmail-templates#28]
The extension doesn't work anymore, I get this error: Template not yet loaded

I have been trying to load this from the UK, it seems the server is not responding?

**Comment by ModDM** [comment]
The extension stopped working and it says Templates not yet loaded as previous users on this site and webstore site of the extension, already reported since this morning. Very annoying this. Developer, please do something.

**Comment by planadecu** [comment]
Hi, we were relying on parse server and they´ve shut down their services: https://parseplatform.github.io/ 
I´m trying to fix it ASAP. Any help is welcome.

**Comment by planadecu** [comment]
Hi,

Due to a shutdown of the service from the extension server´s provider: www.parse.com the templates have been lost and are not recoverable.

You might wonder, how could this happen? the answer is that this extension is not professionally maintained, It has been build on the free time as a hobbie and delivered for free. On 2016 parse.com announced the discountinuation of service but the extension was not upgraded. Contacting with parse.com guys there is no way to get the database back.

When I´ve realized of the discontinuation of service I´ve been working hard to replace parse.com service by a custom one. I´ve published a new 1.6.0 version:
  - Templates are now stored in a private instance in heroku cloud
  - No duplicated "Send buttons"

The extension will be unstable but functional for a few days until we get the grasp with the new server.

Please make sure that you export your templates and you keep a copy of them for better safety. 

Apologizes for the inconvenients.
