### ISSUE TITLE
USER DATA LOST

### ISSUE THREAD

**Issue by ModDM** [planadecu/gmail-templates#30]
This entire page below shows a big problem that many users reported: The extension STOPPED WORKING.
[See extension support page](https://chrome.google.com/webstore/detail/gmail-email-template-and/eaedgipooelodcncjbmmepafomeoojpg/support)
Message to developer SIR JORDI PLANADECU: All data has DISAPPEARED without any prior notice! Please send ALL YOUR USERS a copy of the data they are missing. Thank you very much in advance for your help as soon as possible.

**Comment by planadecu** [comment]
Hi,

Due to a shutdown of the service from the extension server´s provider: www.parse.com the templates have been lost and are not recoverable.

You might wonder, how could this happen? the answer is that this extension is not professionally maintained, It has been build on the free time as a hobbie and delivered for free. On 2016 parse.com announced the discountinuation of service but the extension was not upgraded. Contacting with parse.com guys there is no way to get the database back.

When I´ve realized of the discontinuation of service I´ve been working hard to replace parse.com service by a custom one. I´ve published a new 1.6.0 version:
  - Templates are now stored in a private instance in heroku cloud
  - No duplicated "Send buttons"

The extension will be unstable but functional for a few days until we get the grasp with the new server.

Please make sure that you export your templates and you keep a copy of them for better safety. 

Apologizes for the inconvenients.
